### ISSUE TITLE
Grouping Checks

### ISSUE THREAD

**Issue by arosslau** [liip/LiipMonitorBundle#113]
We have implemented some checks (some built-in - some own) and recognized a need for grouping checks.

## Our Story
We have different servers for our application like ```app```, ```cron``` etc. One of our purposes is to check php-extensions which would be differently on ```app``` and ```cron```.
Another use-case is that some checks only should be available on certain servers.

For that it would be nice to pass some group parameter to the execution of the checks:
```
app/console monitor:list --group=app

app/console monitor:health --group=app
```
_(providing a group-option should be possible in api, too)_

## How-To
I think its neccessary to extend the current config for each built-in check to have a ```group``` config:
```
liip_monitor:
    checks:
        php_extensions:
            group: default # optional
            php-apc:
                enabled: true
                group: default # optional
```

For custom check the tag has to be extended:
```
services:
    monitor.check.php_extensions:
        class: Acme\HelloBundle\Check\PhpExtensionsCheck
        arguments:
            - [ xhprof, apc, memcache ]
        tags:
            - { name: liip_monitor.check, alias: php_extensions, group: default }
```

## Summary
What do think about this feature-idea? Should we provide any PR for that?

**Comment by DrSchimke** [comment]
The groups idea could even be solved in a different way (using an optional config level):

```
liip_monitor:
    enable_controller: true
    checks:
        default:
            php_version:
                5.4.36: >=
            php_extensions:
                - redis
        another_group:
            php_version:
                5.4.37: >=
            php_extensions:
                - redis
                - ldap
```

This is a bit like the doctrine dbal connections configuration.
