### ISSUE TITLE
Doctrine migrations bundle integration?

### ISSUE THREAD

**Issue by bendavies** [liip/LiipMonitorBundle#189]
Hi here,

Provided https://github.com/liip/LiipMonitorBundle/pull/188 is merged, I can't see how the `doctrine_migrations` check is meant to work at all. 

The check is configured with a config file, but the format of the config file is expected to be in the format of the doctrine migrations library, and doesn't work if you provide the doctrine migrations bundle configuration format (but this bundle mandates that you must have the doctrine migrations bundle installed).

So the question is, does anyone have this working, and how, or is the feature broken?

**Comment by lsmith77** [comment]
not sure honestly .. I suspect you will find the answer in a combination of this PR 
https://github.com/liip/LiipMonitorBundle/pull/141/files and the ZendDiagnostic documentation

**Comment by bendavies** [comment]
@edefimov wonder if you can remember how this is meant to work?

**Comment by edefimov** [comment]
@bendavies , There is a configuration option named `doctrine_migrations` in this bundle. There you can define configuration files for Doctrine migrations bundle and this bundle will create corresponding checks. You may use this snippet:
```yaml
liip_monitor:
  checks:
    doctrine_migrations:
      my_appication_migration:
        configuration_file: <absolute path to file>
        connection: <doctrine dbal connection name>
```

**Comment by bendavies** [comment]
hi @edefimov 

Thanks, i understand all that. i just couldn't get it to work :)
do you have a working example anywhere?

**Comment by edefimov** [comment]
Just tested on symfony/skeleton, on symfony 4 it doesn't work because of private services. I'll make a fix during a week.

**Comment by bendavies** [comment]
Thanks! Can you push your example project, even if it doesn't work, to show
me?

**Comment by edefimov** [comment]
@bendavies , Sure, look configs this repository https://github.com/edefimov/doctrine-migration-health-check-sample

**Comment by bendavies** [comment]
Thanks. I see how to do it now. You have to have w migration config files. Once for doctrine migrations bundle, and a other for this bundle.

**Comment by edefimov** [comment]
@bendavies , issue is fixed in this branch https://github.com/edefimov/LiipMonitorBundle/tree/sf4_migrations_fix , you can try it in your project. If you have DoctrineMigrationsBundle installed you can use such config:
```yaml
liip_monitor:
  checks:
    doctrine_migrations:
      my_app: 'my_db_connection'
```
without creating additional config file
