### ISSUE TITLE
Doctrine/DBAL implicit dependency introduced in 2.7.1 ?

### ISSUE THREAD

**Issue by alcohol** [liip/LiipMonitorBundle#191]
After upgrading from [2.7.0 to 2.7.1](https://github.com/liip/LiipMonitorBundle/compare/2.7.0...2.7.1), our application no longer can compile the following configuration:

```
liip_monitor:
    # enabling the controller requires that `assets` are enabled in the framework bundle
    enable_controller: false
    checks:
        guzzle_http_service:
            elastic:
                url: '%env(APP_ELASTIC_DSN)%'
```

```
# bin/console cache:warmup

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Connection" from namespace "Doctrine\DBAL".
Did you forget a "use" statement for e.g. "Symfony\Component\VarDumper\Server\Connection" or "Elasticsearch\Connections\Connection"? in /var/www/vendor/liip/monitor-bundle/DependencyInjection/LiipMonitorExtension.php:45
Stack trace:
#0 /var/www/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Liip\MonitorBundle\DependencyInjection\LiipMonitorExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#1 /var/www/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 /var/www/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Symfony\Component\HttpKernel\DependencyInjection\MergeExt in /var/www/vendor/liip/monitor-bundle/DependencyInjection/LiipMonitorExtension.php on line 45
```
