### ISSUE TITLE
An opportunity to set labels for every check.

### ISSUE THREAD

**Issue by voodooism** [liip/LiipMonitorBundle#248]
It would be super cool to have an opportunity to set labels for every check explicitly in the bundle config.
For instance:

```yaml
liip_monitor:
    checks:
        doctrine_dbal:
            - {connection: chack, label: 'my_custom_label_for_this_check'}
```

I have no idea how can I set labels without refactoring this bundle. 
What do you think about it? Speak your mind guys, please. I'm actually ready to start working on this enhancement.
