### ISSUE TITLE
No route found -  Using app with autoconfigure:true

### ISSUE THREAD

**Issue by igordeveloper** [liip/LiipMonitorBundle#274]
Hi guys.

I'm using the configuration autoconfigure:true in my app, and the 'liip_monitor.check''check is being tagged automatically.
When I' run the Health check page the check works fine, but, when i try repeat a individual custom check in the button GO the app receives the error below with route not found.

`No route found for "POST http://localhost:8000/monitor/health/run/App/Diagnostics/Check/CustomCheck" (from "http://localhost:8000/monitor/health/")`

My configurations:

```
config/services.yaml

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

```

```
config/packages/monitor.yaml

liip_monitor:
    default_group: default
    enable_controller: true
```

```
config/routes/monitor.yaml
_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health
```

Custom check class
```
<?php

declare(strict_types=1);

namespace App\Diagnostics\Check;

use Laminas\Diagnostics\Check\CheckInterface;
use Laminas\Diagnostics\Result\Failure;
use Laminas\Diagnostics\Result\Success;

class CustomCheck implements CheckInterface
{
```

**Comment by igordeveloper** [comment]
If I add a entry in services.yaml with check service are created 2 checks in the Health Check page.

If I use autoconfigure: true in _defaults, Do I need to add autoconfigure:false for each check service I add?

**Comment by igordeveloper** [comment]
Could you please help me if i'm missing some configuration?

Thank you.

**Comment by kbond** [comment]
Hi @igordeveloper, sorry for the delay - I've been on vacation.

Yes, you'll need to add an alias as it's trying to match the route on the class name.

**Comment by igordeveloper** [comment]
> Hi @igordeveloper, sorry for the delay - I've been on vacation.
> 
> Yes, you'll need to add an alias as it's trying to match the route on the class name.

Hi @kbond , no worries.

I add a alias as below, and now i have 2 entries 'Custom check' http://localhost:8000/monitor/health

```
    monitor.check.custom:
        class: App\Diagnostics\Check\CustomCheck
        arguments:
            - [ xhprof, apc, memcache ]
        tags:
            - { name: liip_monitor.check, alias: custom}
```
One of them gives an error because the route is created with 'monitor.check.mercure' and the another works.

Is there any other way to fix this, besides inserting autoconfigure: false for this service? Since my app's _defaults is set to true.

Thank you again!

**Comment by kbond** [comment]
> Is there any other way to fix this, besides inserting autoconfigure: false for this service

I don't think so. Some work needs to be done with how checks are auto-configured.

**Comment by igordeveloper** [comment]
> > Is there any other way to fix this, besides inserting autoconfigure: false for this service
> 
> I don't think so. Some work needs to be done with how checks are auto-configured.

Sorry, needs to be done in my configuration or bundle side?

**Comment by kbond** [comment]
Right now, you'll need to add `autoconfigure: false` to your config to avoid 2 instances being registered:

```yaml
    monitor.check.custom:
        class: App\Diagnostics\Check\CustomCheck
        autoconfigure: false
        arguments:
            - [ xhprof, apc, memcache ]
        tags:
            - { name: liip_monitor.check, alias: custom}
```

The bundle needs some work to avoid needing this.
