### ISSUE TITLE
cannot install 3.0 with new Symfony project

### ISSUE THREAD

**Issue by tacman** [liip/LiipMonitorBundle#300]
Installing shows this error:

     Uncaught Error: Class "Liip\MonitorBundle\LiipMonitorBundle" not found

```bash
symfony new --webapp monitor-test && cd monitor-test
composer config minimum-stability dev
composer require liip/monitor-bundle:^3.0
bin/console debug:route
```

Enabling assets in framework and setting enabled to true in monitor.yaml does not change the error, so I didn't include them in the instructions.

```
Configure the bundle and routes:
    1. You MUST verify the configuration in config/packages/monitor.yaml.
    2. You MAY configure additional your checks and reporters, see the README.md for instructions.
    3. You MAY configure the routes as specified in the README.md if you enable the controller.

No security vulnerability advisories found
Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#10
  #message: """
    Attempted to load class "LiipMonitorBundle" from namespace "Liip\MonitorBundle".\n
    Did you forget a "use" statement for "Liip\Monitor\LiipMonitorBundle"?
    """
  #code: 0
  #file: "./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php"
  #line: 136
  trace: {
    ./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:136 { …}
    ./vendor/symfony/http-kernel/Kernel.php:332 { …}
    ./vendor/symfony/http-kernel/Kernel.php:724 { …}
    ./vendor/symfony/http-kernel/Kernel.php:123 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:179 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:71 { …}
    ./vendor/symfony/console/Application.php:169 { …}
    ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49 { …}
    ./vendor/autoload_runtime.php:29 { …}
    ./bin/console:15 {
      › 
      › require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
      › 
      arguments: {
        "/home/tac/trash/monitor-test/vendor/autoload_runtime.php"
      }
    }
  }
}
2024-03-23T13:00:14+00:00 [critical] Uncaught Error: Class "Liip\MonitorBundle\LiipMonitorBundle" not found

**Comment by kbond** [comment]
I think the recipe for 2.x is being used: https://github.com/symfony/recipes-contrib/tree/main/liip/monitor-bundle/2.6

You'll have to remove the adjustments the recipe made and manually enable. (new bundle class is `Liip\Monitor\LiipMonitorBundle`)

**Comment by tacman** [comment]
Thanks.  The recipe system is one of the weakest parts of the Symfony ecosystem.  It seems like it'd be so much easier for bundle developers to configure the recipe within their bundle, and when it's published to packagist that Symfony automatically takes care of it.

**Comment by xabbuh** [comment]
I have opened a PR to update the recipe for 3.0: symfony/recipes-contrib#1605

**Comment by tacman** [comment]
Thanks!  How about adding the routing and a small config file that at least has a basic health check working that is installed with the recipe?

Should I be following the instructions in 3.0 or in master?  3.0 has a lot of details, but doesn't have routing instructions.

The default config listed in the 3.0 instructions has nulls for integers, which fail.  I'm adding this here because I think adding the package and routing config to the recipe would be very helpful.

**Comment by kbond** [comment]
> 3.0 has a lot of details, but doesn't have routing instructions.

I removed the routing from v3. There is an [OhDear](https://ohdear.app/docs/features/application-health-monitoring) base controller that can be extended and configure routing for. At this point, no generic health check controller. I may revisit adding later.

**Comment by tacman** [comment]
I'm still not quite following how to integrate it with OhDear.    Doesn't OhDear need an API endpoint to check?  If I need something like https://packagist.org/packages/bitbirddev/oh-dear-bundle, could you add it to suggests?

The CLI is working (YAY!), but I miss the /monitor/health route that was in Version 2.  Can you document how to re-add it?

@xabbuh thanks for updating the recipe!  What do you think of adding /config/packages/liip_monitor.yaml as well, with something like this?

```yaml
# config/packages/liip_monitor.yaml

liip_monitor:
  checks:
    system_memory_usage: true # warn @ 70%, fail @ 90%

    system_disk_usage: true # warn @ 70%, fail @ 90%

    # requires configuration
    system_free_disk_space:
      warning: 20GB
      critical: 10GB

    system_reboot: true

    system_load_average:
      1_minute: true # warn @ 70%, fail @ 90%
      5_minute: true # warn @ 70%, fail @ 90%
      15_minute: true # warn @ 70%, fail @ 90%

    apcu_memory_usage: true # warn @ 70%, fail @ 90%

    apcu_fragmentation: true # warn @ 70%, fail @ 90%

    opcache_memory_usage: true # warn @ 70%, fail @ 90%

    php_version: true

    composer_audit: true

    symfony_version: true

    dbal_connection: true # auto creates a check for each dbal connection
#    dbal_connection: default # use specific dbal connection
#    dbal_connection: [default, alternate] # use specific dbal connections
```

Then we can update the installation demo to something similar to the commands in the first message of this thread.
